services:
  - type: web
    name: tiktok-username-checker-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci
    startCommand: node server.js
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
